name: 'Create Build Number Tag'
description: 'Create build number tag in repo'
inputs:
  prefix:
    description: 'Prefix for tag'
    required: false
    default: 'build-'
  token:
    description: 'GitHub token to create and delete refs'
    required: true
  version_prefix:
    description: 'Optional version number to prefix the prefix'
    required: false
outputs:
  build_number:
    description: 'Build tag number'
runs:
  using: 'node16'
  main: 'index.js'
